import type { SdProTableContext } from '../types';
export declare const useTableMethod: ($proTable: SdProTableContext) => {
    clearSearch: () => void;
    clearAll: () => void;
    setActiveTab: (value: string | number) => void;
    getActiveTab: () => string | number;
    setTabBadge: (key: string | number, count: number) => void;
    clearTabBadge: () => void;
    reloadTableData: <RowItem = any>(rows: RowItem[]) => void;
    setTableData: (rows: any[]) => void;
    getTableData: () => {
        full_data: any[];
        filter_data: any[];
        visible_data: any[];
    };
    showColumn: (fieldOrColumn: any) => void;
    hideColumn: (fieldOrColumn: any) => void;
    getColumnByField: (field: string) => any;
    getColumns: () => any;
    getTableColumn: () => any;
    loadColumn: (columns: any[]) => any;
    reloadColumns: (columns: any[]) => any;
    refreshColumn: () => any;
    insert: (row: any | any[]) => void;
    insertAt: (row: any | any[], rowIndex?: number) => void;
    remove: (row: any) => void;
    replaceRow: (old_row: any, new_row: any) => void;
    getRowIndex: (row: any, rows?: any[]) => number;
    setCurrentRow: (row: any) => void;
    clearCurrentRow: () => void;
    clearFilter: () => void;
    setFilter: (field: string) => void;
    getRadioRecord: () => any;
    setRadioRow: <RowItem_1 = any>(row: RowItem_1) => void;
    clearRadioRow: () => void;
    clearRadioReserve: () => void;
    getCheckboxRecords: () => any;
    setCheckboxRow: <RowItem_2 = any>(rows: RowItem_2 | RowItem_2[], checked: boolean) => void;
    setAllCheckboxRow: (checked: boolean) => void;
    toggleAllCheckboxRow: () => void;
    clearCheckboxRow: () => void;
    isAllCheckboxChecked: () => any;
    isAllCheckboxIndeterminate: () => any;
    setRowExpand: (row: any, checked: boolean) => void;
    setAllRowExpand: (checked: boolean) => void;
    toggleRowExpand: <RowItem_3 = any>(row: RowItem_3) => void;
    scrollToTop: () => void;
    getScroll: () => any;
    clearScroll: () => void;
    refreshScroll: () => void;
    toggleMaximize: () => void;
    maximize: () => void;
    revert: () => void;
    isMaximized: () => boolean;
    openExportSetting: () => void;
    closeExportSetting: () => void;
    openColumnSetting: () => void;
    closeColumnSetting: () => void;
};
